name: filter_word
description: A package that allow you to filter word as a string. Change to asterisk, sensor, or remove word from string at once.
version: 1.1.1
homepage: https://github.com/ichsanputr/dart_filterword

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
